### ISSUE TITLE
Error: guard does not provide service for github

### ISSUE THREAD

**Issue by bracki** [appscode/guard#127]
I have configured Guard according to the documentation to work with kops.

When I now make a request with the Bearer token configured for kubectl, this is what I see in the guard logs. What's going wrong there? I assume that `github` or `GitHub` or `Github` is matched directly and some part is doing the wrong thing, can't tell which though.
```
I0419 22:16:27.629481       1 handler.go:31] Received token review request for github/my-cool-org
E0419 22:16:27.629935       1 utils.go:65] [guard does not provide service for github]
I0419 22:16:27.630271       1 utils.go:69] Stacktrace: guard does not provide service for github%!(EXTRA errors.StackTrace=[handler.go:41 <autogenerated>:1 instrument_server.go:196 server.go:1947 instrument_server.go:100 server.go:1947 instrument_server.go:76 server.go:1947 instrument_server.go:40 server.go:1947 mux.go:129 server.go:2694 server.go:3260 <autogenerated>:1 h2_bundle.go:5475 h2_bundle.go:5760 asm_amd64.s:2361])
```

**Comment by tamalsaha** [comment]
Hi, please use `github` since we do case-sensitive match currently. We are going to make the check case-insensitive.

**Comment by tamalsaha** [comment]
@bracki , can you check if 0.1.1 fixes the issue?

**Comment by bracki** [comment]
Hard to say, because I got everything working by lower casing. I’ll try though. Thanks for fixing and pointing out the solution.

**Comment by tamalsaha** [comment]
Good to know that lower casing fixed the problem!
