### ISSUE TITLE
Enable guard to use OAuth 2.0 On-Behalf-Of flow to obtain user's group memberships

### ISSUE THREAD

**Issue by amanohar** [appscode/guard#131]
Currently guard uses the Application Identity of Web API AAD application to get AAD user's group memberships: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios#web-application-to-web-api

The caveat of using this flow is that it requires the application to have certain kinds of read permissions for all users profile in AAD. This is an elevated access scenario and some tenant admins (and organizations) don't allow applications to have this level of access without user's consent.

A safer/more acceptable model is to use _OAuth 2.0 On-Behalf-Of flow_: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-on-behalf-of#protocol-diagram. 

In this scenario Guard to request group memberships from AAD on behalf of the user using it's application identity and user's token in exchange of token returned by AAD.

This issue is a feature request to add On-Behalf-Of flow in Guard to obtain group memberships of the user.

**Comment by tamalsaha** [comment]
The key clarification needed here is: all apis that return list of groups require `Directory.Read.All` permission which can be only granted by AAD admin. How does OBO flow work around this.

- [user: getMemberGroups](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user_getmembergroups.md#user-getmembergroups)

- [user: getMemberObjects](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user_getmemberobjects.md#permissions)

- [List Groups](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_list.md#permissions)

**Comment by weinong** [comment]
In the current implementation in guard, it is using a server app with "application permission" which is a rather high privilege permission as it enables the app to have access to Graph api all the time (like background daemon). Using obo flow will enable the server app to use "delegated permission" instead which has much lower risk.
Btw, AAD has changed the permissions required for `getMemberGroups`. The lowest permissions to  call this api is `User.Read` and `GroupMember.Read.All`. The latter still requires tenant admin approval, though.

**Comment by tamalsaha** [comment]
@weinong, if you are interested, please open a pr.

**Comment by weinong** [comment]
@tamalsaha yep, that's what i will be doing!

**Comment by weinong** [comment]
@tamalsaha i'm thinking about adding azure label so that our team can track these issues. can you help?

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/guard/releases/tag/v0.5.0-rc.0
