### ISSUE TITLE
Using Gitlab's full_path instead of name while using authentication by Groups

### ISSUE THREAD

**Issue by gopigrip7** [appscode/guard#181]
Hi,
Thanks for the guard. I had integrated with our on-premises gitlab and working great. One requirement that would help us is authentication using group/subgroup. While checking code, guard uses group name instead if its use full_path; then we can grant access subgroup level.

Thanks
Gopinath

**Comment by tamalsaha** [comment]
Sounds good to me, do you want to send a pr?

**Comment by tamalsaha** [comment]
cc: @nightfury1204

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/guard/releases/tag/0.3.0
