### ISSUE TITLE
Logo Proposal for Guard

### ISSUE THREAD

**Issue by area55git** [appscode/guard#184]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Guard.

I will be pleased to collaborate with you.

**Comment by tamalsaha** [comment]
Thank you ! If you want to contribute logo for this project, you are most welcome ! What do you have in mind?

**Comment by area55git** [comment]
I'll make a couple of proposals and send them to you

If you have some ideas, suggestions as to style or colors would be great to be able to start.
I also need a brief summary of Guard to get a better idea.

**Comment by tamalsaha** [comment]
Guard is an authentication server that protects against unauthorized access to a cluster. 

As for ideas, if you can has something like a [warrior with a shield](https://www.google.com/search?q=warrior+with+shield&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiBu7jPtqTcAhVaHjQIHVTyCvYQ_AUICigB&biw=1853&bih=960) where the shield looks like [Kubernetes logo](https://github.com/kubernetes/kubernetes/tree/master/logo) that will be nice.

**Comment by area55git** [comment]
Perfect, I'm going to work on the sketches

**Comment by area55git** [comment]
Hi @tamalsaha Working on your suggestions this was the result, what do you think?

[![LOGO_PROPOSAL_FOR_GUARD.jpg](https://s33.postimg.cc/kb6dd65bz/LOGO_PROPOSAL_FOR_GUARD.jpg)](https://postimg.cc/image/6u9euav0b/)

Remember that this is a sketch, you can suggest the changes you want.

**Comment by area55git** [comment]
Icon or Favicon

[![LOGO_PROPOSAL_FOR_GUARD_2.jpg](https://s33.postimg.cc/8akxc2ftb/LOGO_PROPOSAL_FOR_GUARD_2.jpg)](https://postimg.cc/image/qde03abnv/)

**Comment by tamalsaha** [comment]
Wow, you are quick ! Looks pretty good. I am going to ask another in the team and get back to you .

**Comment by tamalsaha** [comment]
@area55git , we like the one below for logo. For favicon, we would like the one in the middle without the gray background. 
![guard-logo](https://user-images.githubusercontent.com/94814/42904854-37fa753a-8a8b-11e8-8c72-2b92417d49cb.png)

**Comment by area55git** [comment]
Perfect, I will prepare the final files in various formats (SVG, PNG and others)
I will also make a PR to place the logo in the Readme folder to merge.

Do you have any other suggestions?

**Comment by tamalsaha** [comment]
Please make a top level `logo` folder and put all the files there.

**Comment by area55git** [comment]
Hi @tamalsaha, What option do you like?

[![LOGO_PROPOSAL_FOR_GUARD.jpg](https://s33.postimg.cc/8sr70cn0f/LOGO_PROPOSAL_FOR_GUARD.jpg)](https://postimg.cc/image/f6ga3lrwb/)

**Comment by area55git** [comment]
What option do you like?

[![LOGO_PROPOSAL_FOR_GUARD.jpg](https://s33.postimg.cc/8sr70cn0f/LOGO_PROPOSAL_FOR_GUARD.jpg)](https://postimg.cc/image/f6ga3lrwb/)

I am new to github, I will not create a folder, can you create it? and I then attach the logos
or can you teach me how to do it?

**Comment by tamalsaha** [comment]
From left, Darker Red.
From right, Clear gradient

**Comment by area55git** [comment]
Do you like this image for the Readme folder?

[![LOGO_GUARD_Readme.jpg](https://s33.postimg.cc/qafz38ov3/LOGO_GUARD_Readme.jpg)](https://postimg.cc/image/yspf7kvdn/)

**Comment by area55git** [comment]
I was doing an investigation and the helmet of the Romans have a detail, I made the change and it looks much better, sorry for so many changes, but I want to do a good job.

[![LOGO_GUARD_Readme_2.jpg](https://s33.postimg.cc/supe2b8rz/LOGO_GUARD_Readme_2.jpg)](https://postimg.cc/image/903cg6tkb/)

In this proposal the logo is rougher, I like it a lot, what you think?

**Comment by tamalsaha** [comment]
:+1:

**Comment by area55git** [comment]
### [FILE DOWNLOAD](https://drive.google.com/open?id=1MJ3aawCSu6Fs8elaqX-Vq2AUo3aqJjUP)

[![derechos.jpg](https://s33.postimg.cc/5fh47td0f/derechos.jpg)](https://postimg.cc/image/3no5cwtnf/)
This work is licensed under a[ Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
PR #185

**Comment by tamalsaha** [comment]
Thank @area55git . Did you use Illustrator or something else to design the logo? Can you share the original files for it?

Also, do you have any twitter account or something else. Happy to give you a shout out.

**Comment by area55git** [comment]
In the link are the editable files (CDR, SVG, EPS, etc.)

**Comment by area55git** [comment]
instagram.com/@area55_ib

**Comment by area55git** [comment]
In the link are these images too

[![LOGO_GUARD_Readme_2.jpg](https://s33.postimg.cc/h74zifzv3/LOGO_GUARD_Readme_2.jpg)](https://postimg.cc/image/lg9pkm34b/)


[![LOGO_GUARD_Readme.jpg](https://s33.postimg.cc/iv44xl667/LOGO_GUARD_Readme.jpg)](https://postimg.cc/image/3me7jtchn/)


[![Separador.jpg](https://s33.postimg.cc/f00quj2an/Separador.jpg)](https://postimg.cc/image/dxqkbzjh7/)

**Comment by tamalsaha** [comment]
Thank you again! I tweeted here:

- https://twitter.com/tsaha/status/1022280294949244928
- https://www.facebook.com/appscode/posts/820707174793073
