### ISSUE TITLE
Github connector docs asks for unnecessary public_repo permissions

### ISSUE THREAD

**Issue by tmatias** [appscode/guard#195]
The [documentation on the Github connector](https://appscode.com/products/guard/0.2.1/guides/authenticator/github/#issue-token) says

> To use Github authentication, you can use your personal access token with permissions to read public_repo and read:org

Looking at [the connector's source](https://github.com/appscode/guard/blob/master/auth/providers/github/github.go), though, it doesn't seem to use it. 

`public_repo`, despite its name, grants a [somewhat broad set of permissions](https://github.com/dear-github/dear-github/issues/113#issue-132907872), so it would be nice not to require it.

I tried guard with a `read:org` only token as well, and couldn't see any problems either.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/guard/releases/tag/0.3.0
