### ISSUE TITLE
Guard is going into CrashLoopBackoff with mkdir /.guard: PermissionDenied in v0.7.0

### ISSUE THREAD

**Issue by Anumita** [appscode/guard#302]
@tamalsaha , Regression is caused by https://github.com/appscode/guard/commit/0ba41bdaf53ddfe60a02b8b1d661197074354313#diff-d4a5d2aa92f9cb2fcf1abbda16f1e0cfdccce362ee5d395b80624f961c64ac05R39 . Getting permission denied error while trying to creat /.guard directory

**Comment by tamalsaha** [comment]
How are you running into this? That folder was always created by the project. Before it was created inside the CertStore library. Now it is expected to be created outside.

https://github.com/appscode/guard/commit/0ba41bdaf53ddfe60a02b8b1d661197074354313#diff-3df9011fe3c568f40c2ae2d2eded3f85421b193dfd527c15169317151802cd77L48-L51

If your `make unit-tests` command is breaking, I made this change
https://github.com/appscode/guard/blame/master/Makefile#L256

**Comment by Anumita** [comment]
> How are you running into this? That folder was always created by the project. Before it was created inside the CertStore library. Now it is expected to be created outside.
> 
> https://github.com/appscode/guard/blob/v0.6.1/vendor/gomodules.xyz/cert/certstore/lib.go#L48-L51
> 
> If your `make unit-tests` command is breaking, I made this change
> https://github.com/appscode/guard/blame/master/Makefile#L256

I haven't tried with make test as such. I was running into this error on deploying the guard container itself. The container was going into CrashLoopBackoff and the logs showed the mentioned error

**Comment by tamalsaha** [comment]
Did v0.7.1 release fix it?
