### ISSUE TITLE
Is the google auth actually working/tested?

### ISSUE THREAD

**Issue by nhumrich** [appscode/guard#36]
I am trying to set up the google auth for this, and am running into a few problems:
1) The google token is an access token that expire. Am I expected to update my token every time it expires? or am I doing something wrong? Which token do i copy and paste into my kube/config?

2) the admin.directory.group scope only works for people who have admin permissions in g suite. If a normal user (non-admin) tries to use this, the groups api call wont work.

Am I doing this wrong or something? Does anyone have google auth working?

**Comment by tamalsaha** [comment]
@nhumrich , sorry this took us a long time to fix. This has been fixed in master. It will be part of the next release.

**Comment by tamalsaha** [comment]
hi, we have released 0.1.0 https://github.com/appscode/guard/releases/tag/0.1.0 . Please see the updated instructions here: https://appscode.com/products/guard/0.1.0/guides/authenticator/google/
